In [1]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in /opt/anaconda3/lib/python3.8/site-packages (1.21.2)


In [2]:
!pip install pandas --upgrade

     |████████████████████████████████| 11.4 MB 9.1 MB/s eta 0:00:01
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.2
    Uninstalling pandas-1.3.2:
      Successfully uninstalled pandas-1.3.2


In [3]:
!pip install wget

In [4]:
import numpy as np
import pandas as pd
import wget

In [5]:
np.__version__

'1.21.2'

In [6]:
pd.__version__

'1.3.3'

In [4]:
wget.download("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

'data (1).csv'

In [7]:
df = pd.read_csv("data.csv")

In [8]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [10]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
df.tail()

Make   Model  Year                Engine Fuel Type  Engine HP  \
11909    Acura     ZDX  2012     premium unleaded (required)      300.0   
11910    Acura     ZDX  2012     premium unleaded (required)      300.0   
11911    Acura     ZDX  2012     premium unleaded (required)      300.0   
11912    Acura     ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln  Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                  Market Category Vehicle Size  Vehicle Style  highway MPG  \
11909  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11910  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11911  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11912  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11913                      Luxury      Midsize          Sedan           26   

       city mpg  Popularity   MSRP  
11909        16         204  46120  
11910        16         204  56670  
11911        16         204  50620  
11912        16         204  50920  
11913        17          61  28995

In [12]:
bmw_df = df[df.Make == "BMW"]

In [13]:
bmw_df.sample(5)

Make                  Model  Year             Engine Fuel Type  \
11519  BMW                     X5  2017  premium unleaded (required)   
1398   BMW                 Alpina  2003  premium unleaded (required)   
513    BMW  5 Series Gran Turismo  2017  premium unleaded (required)   
11504  BMW                     X4  2016  premium unleaded (required)   
42     BMW               2 Series  2016  premium unleaded (required)   

       Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
11519      300.0               6.0         AUTOMATIC   all wheel drive   
1398       375.0               8.0         AUTOMATIC  rear wheel drive   
513        300.0               6.0         AUTOMATIC  rear wheel drive   
11504      240.0               4.0         AUTOMATIC   all wheel drive   
42         240.0               4.0         AUTOMATIC  rear wheel drive   

       Number of Doors                               Market Category  \
11519              4.0                              Crossover,Luxury   
1398               2.0  Exotic,Factory Tuner,Luxury,High-Performance   
513                4.0                  Hatchback,Luxury,Performance   
11504              4.0                              Crossover,Luxury   
42                 2.0                                        Luxury   

      Vehicle Size  Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
11519      Midsize        4dr SUV           24        18        3916   57800  
1398       Compact    Convertible           19        13        3916  136900  
513          Large  4dr Hatchback           27        19        3916   60900  
11504      Midsize        4dr SUV           28        20        3916   45250  
42         Compact    Convertible           34        23        3916   38650

In [14]:
bmw_df.MSRP.mean()

61546.76347305389

In [15]:
after_2015_df = df[df.Year >= 2015]

In [16]:
after_2015_df["Engine HP"].isnull().sum()

51

In [17]:
mean_hp_before = after_2015_df["Engine HP"].mean()

In [18]:
mean_hp_before

272.98771870794076

In [19]:
after_2015_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5995 entries, 32 to 11902
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               5995 non-null   object 
 1   Model              5995 non-null   object 
 2   Year               5995 non-null   int64  
 3   Engine Fuel Type   5995 non-null   object 
 4   Engine HP          5944 non-null   float64
 5   Engine Cylinders   5987 non-null   float64
 6   Transmission Type  5995 non-null   object 
 7   Driven_Wheels      5995 non-null   object 
 8   Number of Doors    5990 non-null   float64
 9   Market Category    4671 non-null   object 
 10  Vehicle Size       5995 non-null   object 
 11  Vehicle Style      5995 non-null   object 
 12  highway MPG        5995 non-null   int64  
 13  city mpg           5995 non-null   int64  
 14  Popularity         5995 non-null   int64  
 15  MSRP               5995 non-null   int64  
dtypes: float64(3), int64(5

In [20]:
values = {"Engine HP": mean_hp_before}
after_2015_df = after_2015_df.fillna(value=values)

In [21]:
after_2015_df["Engine HP"].isnull().sum()

0

In [22]:
mean_hp_after = after_2015_df["Engine HP"].mean()

In [23]:
print(round(mean_hp_before))
print(round(mean_hp_after))

273
273


In [25]:
rolls_royce_df = df[df["Make"] == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]]
rolls_royce_df.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [26]:
rolls_royce_df.drop_duplicates(inplace=True)

In [27]:
rolls_royce_df

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [28]:
len(rolls_royce_df)

7

In [29]:
X = rolls_royce_df.to_numpy()

In [30]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [31]:
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [32]:
XTX = X.T @ X

In [33]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [34]:
inverted = np.linalg.inv(XTX)

In [35]:
inverted

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [36]:
inverted.sum()

0.032212320677486125

In [37]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [38]:
w = (inverted @ X.T) @ y

In [39]:
w[0]

0.19989598183188972